version: '3.7'

services:
  oracle:
    container_name: oracle
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - 1521:1521
    volumes:
      - type: bind
        source: /my-dir
        target: /ORCL
